### ISSUE TITLE
showblip request

### ISSUE THREAD

**Issue by Andyauk** [jimathy/jim-shops#11]
could you add like a ["showblip"] = false, for anyone who using them like for ems pd. thanks

**Comment by jimathy** [comment]
there's 
```lua
["hideblip"] = true
```
it's used for the blackmarket shop

**Comment by Andyauk** [comment]
> ```lua
> ["hideblip"] = true
> ```
> 
> it's used for the blackmarket shop

I didn't see that, sorry
