### ISSUE TITLE
Double icons in menu list

### ISSUE THREAD

**Issue by epereza** [jimathy/jim-shops#12]
![FiveM_b2612_GTAProcess_H7uvnkFVg8](https://user-images.githubusercontent.com/50680351/170760406-b27aecb5-301a-4d8b-bfd1-0278a1647279.jpg)

**Comment by epereza** [comment]
Never mind, after a server restart is working perfectly

**Comment by epereza** [comment]
Never mind, after a server restart is working perfectly

**Comment by epereza** [comment]
Ok, no, they are still there and the don't want to go away

**Comment by jimathy** [comment]
Set JimMenu to true in the config.lua.

**Comment by epereza** [comment]
And that was the issue. Thank you very much! Now it's working.
