### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mello6510** [jimathy/jim-shops#14]
[ citizen-server-impl] Stopping resource jim-shops
[    c-scripting-core] Creating script environments for jim-shops
[    script:jim-shops] Jim-Shops v1.5 - Shop Script by Jimathy
[    script:jim-shops] SCRIPT ERROR: @jim-shops/server.lua:131: attempt to index a nil value (field '?')
[    script:jim-shops] > handler (@jim-shops/server.lua:3)
[    script:jim-shops] SCRIPT ERROR: @jim-shops/server.lua:6: attempt to index a nil value (field '?')
[    script:jim-shops] (nil stack trace)Started resource jim-shops

**Comment by jimathy** [comment]
You're either missing an item from you list, line 131 is trying to load the name of an item in your products list and can't find one so giving a nil value
