### ISSUE TITLE
NPCs multiplying,,,

### ISSUE THREAD

**Issue by KhrysTLords** [jimathy/jim-shops#3]
Greetings, first of all would like to say that i love this shops and the away they work.
However im facing a little issue that the NPCs from the shops are multiplying some times eveen preventing the players from entering stores.

Was this noticed before, is there a way to fix it?

Thanks in advance, 
KL

**Comment by jimathy** [comment]
Oh that was fixed yesterday, just grab a new download <3

**Comment by KhrysTLords** [comment]
> Oh that was fixed yesterday, just grab a new download <3

Thank you very much will do :)
