### ISSUE TITLE
Errors in the new Version

### ISSUE THREAD

**Issue by KhrysTLords** [jimathy/jim-shops#4]
Greetings again the new version of the shops are giving me some errors to start 
![image](https://user-images.githubusercontent.com/63318957/161707307-c25beef3-cbe9-4931-a405-f2e851da40cf.png)
When you try to purchase an item with quantity.

![image](https://user-images.githubusercontent.com/63318957/161707461-873cabca-49dd-4049-b90f-3b14d0a983a5.png)
When you restart or start the script.

Am i doing anything wrong?
Thanks in advance
KL

**Comment by jimathy** [comment]
I've just fixed the first error
The second one looks like you are missing the mysql event, maybe missing the line fxmanifest.lua

The line is trying to remove the stash database entries, if they exist. This is just to tidy up the database. 
You can remove line 111 in server.lua and replace it with "end"

**Comment by KhrysTLords** [comment]
Great will get on that 
Thanks again for the fast answers.

KL
