### ISSUE TITLE
Not Giving Me The Items

### ISSUE THREAD

**Issue by hoodz123** [jimathy/jim-shops#5]
Any ideas Just Put The Update In And Says Index Nill Value Item Info

**Comment by AscendoTuum86** [comment]
The additions to Black Market code have broken the normal stores. I would recommend reverting to [this commit](https://github.com/jimathy/jim-shops/commit/bba6080c3028c28e260dee9ac7855a06c4c194b4) for now.

**Comment by hoodz123** [comment]
How Do I Do This?

**Comment by jimathy** [comment]
Can anyone show me a screenshot of the error? its working perfect for me

**Comment by hoodz123** [comment]
it dont give me one just dont give me the items bro

**Comment by jimathy** [comment]
"Bro"
Your first message said it gave an error "Index Nill Value Item Info" thats not enough for me to go on lol

**Comment by Belorico** [comment]
Hi Jimathy,

Dunno if its the same happening with the other bro, but im having this:

![image](https://user-images.githubusercontent.com/4929196/163696636-6399ab8e-60a8-47d6-9841-4a31204d4da2.png)

**Comment by Belorico** [comment]
I pushed the script again and its working... probably missed something on last update.
