### ISSUE TITLE
Ammunations not working for me. 

### ISSUE THREAD

**Issue by Carinius** [jimathy/jim-shops#7]
Hey, I threw your awesome stores on my server. Everything works very well, except for the ammunations. The NPC is there but when I select and want to open the menu, he first does nothing and when I do it a second time, he kicks me off the server. These are the errors:
[ script:jim-shops] SCRIPT ERROR: @jim-shops/server.lua:151: attempt to index a nil value (local 'Player')
[ script:jim-shops] > TriggerCallback (@qb-core/server/functions.lua:207)
[ script:jim-shops] > handler (@qb-core/server/events.lua:110)
[ script:qb-core] SCRIPT ERROR: error object is not a string
[ script:qb-core] (nil stack trace)SCRIPT ERROR: @jim-shops/server.lua:151: attempt to index a nil value (local 'Player')

Do you know what this could be? Greetings Carinius
![Bild_2022-04-19_124504125](https://user-images.githubusercontent.com/73562971/163987308-691a9c3c-8454-4ffe-a6b2-3943849a82ec.png)

**Comment by jimathy** [comment]
Well..line 151 points directly to:
```unique = itemInfo["unique"],```

I'm not sure how you could get getting that error there

**Comment by Carinius** [comment]
Wow thank you so much for your sooo fast reply
Here is a screenshot of my server.lua line 151
![shops lua](https://user-images.githubusercontent.com/73562971/163988039-13771f09-b325-4c83-899d-5e1c520fa001.png)

**Comment by jimathy** [comment]
I'd recommend updating, your missing a few lines from what I can see there.
Try a newer version and let me know if that works

**Comment by Carinius** [comment]
I have now updated and the same problem 
![disc](https://user-images.githubusercontent.com/73562971/163991247-3b722dda-e215-4d9c-8332-026313e2a861.png)
![update](https://user-images.githubusercontent.com/73562971/163991252-2ed1d97c-5b02-419d-9739-8be16859488c.png)

**Comment by Carinius** [comment]
Okay, I'll have to see what the problem is. Possibly the license. I have to look but thanks for your quick answer and help

**Comment by jimathy** [comment]
Yea, its weird, I can only get that error by removing "source" from line 160
https://i.imgur.com/sKsmVrT.jpeg

**Comment by Carinius** [comment]
I have found the error. My adminchar was buggy. Created a new one and now it works. Only that it shows me no firearms, although the char has a license.... Never mind that I get it right. Many many thanks again for everything <3
